# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pesel',
            field=models.BigIntegerField(),
        ),
    ]
