# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160921_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_',
            options={'ordering': ['level', 'branch']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['value']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='student',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='class_',
            name='classroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='journal.Classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='classroom',
            field=models.ManyToManyField(blank=True, to='journal.Classroom'),
        ),
    ]
