# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160907_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='telephone_number',
            field=models.BigIntegerField(),
        ),
    ]
