# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160907_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degrees',
        ),
        migrations.AddField(
            model_name='student',
            name='degrees',
            field=models.ManyToManyField(blank=True, null=True, to='journal.Degree'),
        ),
    ]
