# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160917_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pesel',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='notes',
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.ManyToManyField(to='journal.Note'),
        ),
    ]
