# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160926_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['position', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
