# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20160907_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degrees',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='journal.Degree'),
        ),
    ]
